// @ts-expect-error: Geçici olarak tür kontrolünü atla, çünkü request nesnesinin yapısı tam olarak bilinmiyor
import { create } from 'zustand'

interface LanguageState {
  currentLanguage: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations = {
  tr: {
    'admin.title': 'Admin Panel',
    'admin.viewSite': 'Siteyi Görüntüle',
    'admin.dashboard.title': 'Gösterge Paneli',
    'admin.dashboard.totalAccounts': 'Toplam Hesaplar',
    'admin.dashboard.activeAccounts': 'Aktif Hesaplar',
    'admin.dashboard.soldAccounts': 'Satılan Hesaplar',
    'admin.dashboard.totalRevenue': 'Toplam Gelir',
    'admin.accounts.title': 'Hesap Yönetimi',
    'admin.accounts.add': 'Yeni Hesap Ekle',
    'admin.accounts.manage': 'Hesapları Yönet',
    'admin.accounts.new': 'Yeni Hesap',
    'admin.accounts.edit': 'Hesabı Düzenle',
    'admin.accounts.rank': 'Rütbe',
    'admin.accounts.rankImage': 'Rütbe Görseli',
    'admin.accounts.price': 'Fiyat',
    'admin.accounts.priceError': 'Lütfen geçerli bir fiyat girin',
    'admin.accounts.contactInfo': 'İletişim Bilgisi',
    'admin.accounts.description': 'Açıklama',
    'admin.accounts.images': 'Hesap Görselleri',
    'admin.accounts.imagesHelp': 'Görselleri virgülle ayırarak ekleyin (örn: https://resim1.jpg, https://resim2.jpg)',
    'admin.accounts.status': 'Durum',
    'admin.accounts.status_available': 'Satışta',
    'admin.accounts.status_sold': 'Satıldı',
    'admin.accounts.status_pending': 'Beklemede',
    'admin.accounts.confirmDelete': 'Bu hesabı silmek istediğinize emin misiniz?',
    'admin.accounts.noAccounts': 'Henüz hesap bulunmuyor',
    'admin.accounts.createError': 'Hesap oluşturulurken bir hata oluştu',
    'admin.settings': 'Ayarlar',
    'common.save': 'Kaydet',
    'common.saving': 'Kaydediliyor...',
    'common.cancel': 'İptal',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'admin.accounts.currency': 'Para Birimi',
    'admin.accounts.uploadImages': 'Fotoğraf Yükle',
    'admin.accounts.uploadImagesHelp': 'Birden fazla fotoğraf seçebilirsiniz',
    accounts: {
      title: 'Point Blank Hesapları',
      noAccounts: 'Henüz hesap bulunmamaktadır.',
      whatsapp: 'WhatsApp',
      rank: 'Point Blank Hesabı'
    }
  },
  en: {
    'admin.title': 'Admin Panel',
    'admin.viewSite': 'View Site',
    'admin.dashboard.title': 'Dashboard',
    'admin.dashboard.totalAccounts': 'Total Accounts',
    'admin.dashboard.activeAccounts': 'Active Accounts',
    'admin.dashboard.soldAccounts': 'Sold Accounts',
    'admin.dashboard.totalRevenue': 'Total Revenue',
    'admin.accounts.title': 'Account Management',
    'admin.accounts.add': 'Add New Account',
    'admin.accounts.manage': 'Manage Accounts',
    'admin.accounts.new': 'New Account',
    'admin.accounts.edit': 'Edit Account',
    'admin.accounts.rank': 'Rank',
    'admin.accounts.rankImage': 'Rank Image',
    'admin.accounts.price': 'Price',
    'admin.accounts.priceError': 'Please enter a valid price',
    'admin.accounts.contactInfo': 'Contact Info',
    'admin.accounts.description': 'Description',
    'admin.accounts.status': 'Status',
    'admin.accounts.status_available': 'Available',
    'admin.accounts.status_sold': 'Sold',
    'admin.accounts.status_pending': 'Pending',
    'admin.accounts.confirmDelete': 'Are you sure you want to delete this account?',
    'admin.accounts.noAccounts': 'No accounts found',
    'admin.accounts.createError': 'Error creating account',
    'admin.settings': 'Settings',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'admin.accounts.currency': 'Currency',
    'admin.accounts.uploadImages': 'Upload Photos',
    'admin.accounts.uploadImagesHelp': 'You can select multiple photos',
    accounts: {
      title: 'Point Blank Accounts',
      noAccounts: 'No accounts available yet.',
      whatsapp: 'WhatsApp',
      rank: 'Point Blank Account'
    }
  },
  ru: {
    'admin.title': 'Панель администратора',
    'admin.viewSite': 'Просмотр сайта',
    'admin.dashboard.title': 'Панель управления',
    'admin.dashboard.totalAccounts': 'Всего аккаунтов',
    'admin.dashboard.activeAccounts': 'Активные аккаунты',
    'admin.dashboard.soldAccounts': 'Проданные аккаунты',
    'admin.dashboard.totalRevenue': 'Общий доход',
    'admin.accounts.title': 'Управление аккаунтами',
    'admin.accounts.add': 'Добавить аккаунт',
    'admin.accounts.manage': 'Управление аккаунтами',
    'admin.accounts.new': 'Новый аккаунт',
    'admin.accounts.edit': 'Редактировать аккаунт',
    'admin.accounts.rank': 'Ранг',
    'admin.accounts.rankImage': 'Изображение ранга',
    'admin.accounts.price': 'Цена',
    'admin.accounts.priceError': 'Пожалуйста, введите действительную цену',
    'admin.accounts.contactInfo': 'Контактная информация',
    'admin.accounts.description': 'Описание',
    'admin.accounts.status': 'Статус',
    'admin.accounts.status_available': 'Доступен',
    'admin.accounts.status_sold': 'Продан',
    'admin.accounts.status_pending': 'В ожидании',
    'admin.accounts.confirmDelete': 'Вы уверены, что хотите удалить этот аккаунт?',
    'admin.accounts.noAccounts': 'Аккаунты не найдены',
    'admin.accounts.createError': 'Ошибка при создании аккаунта',
    'admin.settings': 'Настройки',
    'common.save': 'Сохранить',
    'common.saving': 'Сохранение...',
    'common.cancel': 'Отмена',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'admin.accounts.currency': 'Валюта',
    'admin.accounts.uploadImages': 'Загрузить фотографии',
    'admin.accounts.uploadImagesHelp': 'Вы можете выбрать несколько фотографий',
    accounts: {
      title: 'Аккаунты Point Blank',
      noAccounts: 'Пока нет доступных аккаунтов.',
      whatsapp: 'WhatsApp',
      rank: 'Аккаунт Point Blank'
    }
  },
  az: {
    'admin.title': 'Admin Panel',
    'admin.viewSite': 'Sayta bax',
    'admin.dashboard.title': 'İdarəetmə paneli',
    'admin.dashboard.totalAccounts': 'Ümumi Hesablar',
    'admin.dashboard.activeAccounts': 'Aktiv Hesablar',
    'admin.dashboard.soldAccounts': 'Satılan Hesablar',
    'admin.dashboard.totalRevenue': 'Ümumi Gəlir',
    'admin.accounts.title': 'Hesab İdarəetməsi',
    'admin.accounts.add': 'Yeni Hesab Əlavə Et',
    'admin.accounts.manage': 'Hesabları İdarə Et',
    'admin.accounts.new': 'Yeni Hesab',
    'admin.accounts.edit': 'Hesabı Redaktə Et',
    'admin.accounts.rank': 'Rütbə',
    'admin.accounts.rankImage': 'Rütbə Şəkli',
    'admin.accounts.price': 'Qiymət',
    'admin.accounts.priceError': 'Zəhmət olmasa, etibarlı qiymət daxil edin',
    'admin.accounts.contactInfo': 'Əlaqə Məlumatı',
    'admin.accounts.description': 'Təsvir',
    'admin.accounts.images': 'Hesap Görselleri',
    'admin.accounts.imagesHelp': 'Görselleri virgülle ayırarak ekleyin (örn: https://resim1.jpg, https://resim2.jpg)',
    'admin.accounts.status': 'Status',
    'admin.accounts.status_available': 'Satışda',
    'admin.accounts.status_sold': 'Satıldı',
    'admin.accounts.status_pending': 'Gözləmədə',
    'admin.accounts.confirmDelete': 'Bu hesabı silmək istədiyinizə əminsiniz?',
    'admin.accounts.noAccounts': 'Hesab tapılmadı',
    'admin.accounts.createError': 'Hesab yaradılarkən xəta baş verdi',
    'admin.settings': 'Tənzimləmələr',
    'common.save': 'Yadda saxla',
    'common.saving': 'Yadda saxlanılır...',
    'common.cancel': 'Ləğv et',
    'common.edit': 'Redaktə et',
    'common.delete': 'Sil',
    'admin.accounts.currency': 'Valyuta',
    'admin.accounts.uploadImages': 'Şəkil Yüklə',
    'admin.accounts.uploadImagesHelp': 'Birdən çox şəkil seçə bilərsiniz'
  }
};

export const useLanguage = create<LanguageState>((set) => ({
  currentLanguage: 'tr',
  setLanguage: (lang) => set({ currentLanguage: lang }),
  t: (key) => {
    const state = useLanguage.getState();
    const translation = translations[state.currentLanguage as keyof typeof translations];
    return translation[key as keyof typeof translation] || key;
  }
})); 